/*
 * This file is generated by jOOQ.
 */
package com.takehome.dao.jooq.domain.tables;


import java.time.LocalDateTime;

import com.takehome.dao.jooq.domain.NyCabData;
import com.takehome.dao.jooq.domain.tables.records.CabTripDataRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CabTripData extends TableImpl<CabTripDataRecord> {

    private static final long serialVersionUID = -1600346099;

    /**
     * The reference instance of <code>ny_cab_data.cab_trip_data</code>
     */
    public static final CabTripData CAB_TRIP_DATA = new CabTripData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CabTripDataRecord> getRecordType() {
        return CabTripDataRecord.class;
    }

    /**
     * The column <code>ny_cab_data.cab_trip_data.medallion</code>.
     */
    public final TableField<CabTripDataRecord, String> MEDALLION = createField(DSL.name("medallion"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.hack_license</code>.
     */
    public final TableField<CabTripDataRecord, String> HACK_LICENSE = createField(DSL.name("hack_license"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.vendor_id</code>.
     */
    public final TableField<CabTripDataRecord, String> VENDOR_ID = createField(DSL.name("vendor_id"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.rate_code</code>.
     */
    public final TableField<CabTripDataRecord, Integer> RATE_CODE = createField(DSL.name("rate_code"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.store_and_fwd_flag</code>.
     */
    public final TableField<CabTripDataRecord, String> STORE_AND_FWD_FLAG = createField(DSL.name("store_and_fwd_flag"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.pickup_datetime</code>.
     */
    public final TableField<CabTripDataRecord, LocalDateTime> PICKUP_DATETIME = createField(DSL.name("pickup_datetime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.dropoff_datetime</code>.
     */
    public final TableField<CabTripDataRecord, LocalDateTime> DROPOFF_DATETIME = createField(DSL.name("dropoff_datetime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.passenger_count</code>.
     */
    public final TableField<CabTripDataRecord, Integer> PASSENGER_COUNT = createField(DSL.name("passenger_count"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.trip_time_in_secs</code>.
     */
    public final TableField<CabTripDataRecord, Integer> TRIP_TIME_IN_SECS = createField(DSL.name("trip_time_in_secs"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.trip_distance</code>.
     */
    public final TableField<CabTripDataRecord, Double> TRIP_DISTANCE = createField(DSL.name("trip_distance"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.pickup_longitude</code>.
     */
    public final TableField<CabTripDataRecord, Double> PICKUP_LONGITUDE = createField(DSL.name("pickup_longitude"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.pickup_latitude</code>.
     */
    public final TableField<CabTripDataRecord, Double> PICKUP_LATITUDE = createField(DSL.name("pickup_latitude"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.dropoff_longitude</code>.
     */
    public final TableField<CabTripDataRecord, Double> DROPOFF_LONGITUDE = createField(DSL.name("dropoff_longitude"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>ny_cab_data.cab_trip_data.dropoff_latitude</code>.
     */
    public final TableField<CabTripDataRecord, Double> DROPOFF_LATITUDE = createField(DSL.name("dropoff_latitude"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>ny_cab_data.cab_trip_data</code> table reference
     */
    public CabTripData() {
        this(DSL.name("cab_trip_data"), null);
    }

    /**
     * Create an aliased <code>ny_cab_data.cab_trip_data</code> table reference
     */
    public CabTripData(String alias) {
        this(DSL.name(alias), CAB_TRIP_DATA);
    }

    /**
     * Create an aliased <code>ny_cab_data.cab_trip_data</code> table reference
     */
    public CabTripData(Name alias) {
        this(alias, CAB_TRIP_DATA);
    }

    private CabTripData(Name alias, Table<CabTripDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private CabTripData(Name alias, Table<CabTripDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CabTripData(Table<O> child, ForeignKey<O, CabTripDataRecord> key) {
        super(child, key, CAB_TRIP_DATA);
    }

    @Override
    public Schema getSchema() {
        return NyCabData.NY_CAB_DATA;
    }

    @Override
    public CabTripData as(String alias) {
        return new CabTripData(DSL.name(alias), this);
    }

    @Override
    public CabTripData as(Name alias) {
        return new CabTripData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CabTripData rename(String name) {
        return new CabTripData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CabTripData rename(Name name) {
        return new CabTripData(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Double, Double, Double, Double, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
