/*
 * This file is generated by jOOQ.
 */
package com.takehome.dao.jooq.domain.tables.records;


import java.time.LocalDateTime;

import com.takehome.dao.jooq.domain.tables.CabTripData;
import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CabTripDataRecord extends TableRecordImpl<CabTripDataRecord> implements Record14<String, String, String, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Double, Double, Double, Double, Double> {

    private static final long serialVersionUID = -1520713021;

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.medallion</code>.
     */
    public void setMedallion(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.medallion</code>.
     */
    public String getMedallion() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.hack_license</code>.
     */
    public void setHackLicense(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.hack_license</code>.
     */
    public String getHackLicense() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.vendor_id</code>.
     */
    public void setVendorId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.vendor_id</code>.
     */
    public String getVendorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.rate_code</code>.
     */
    public void setRateCode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.rate_code</code>.
     */
    public Integer getRateCode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.store_and_fwd_flag</code>.
     */
    public void setStoreAndFwdFlag(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.store_and_fwd_flag</code>.
     */
    public String getStoreAndFwdFlag() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.pickup_datetime</code>.
     */
    public void setPickupDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.pickup_datetime</code>.
     */
    public LocalDateTime getPickupDatetime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.dropoff_datetime</code>.
     */
    public void setDropoffDatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.dropoff_datetime</code>.
     */
    public LocalDateTime getDropoffDatetime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.passenger_count</code>.
     */
    public void setPassengerCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.passenger_count</code>.
     */
    public Integer getPassengerCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.trip_time_in_secs</code>.
     */
    public void setTripTimeInSecs(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.trip_time_in_secs</code>.
     */
    public Integer getTripTimeInSecs() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.trip_distance</code>.
     */
    public void setTripDistance(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.trip_distance</code>.
     */
    public Double getTripDistance() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.pickup_longitude</code>.
     */
    public void setPickupLongitude(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.pickup_longitude</code>.
     */
    public Double getPickupLongitude() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.pickup_latitude</code>.
     */
    public void setPickupLatitude(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.pickup_latitude</code>.
     */
    public Double getPickupLatitude() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.dropoff_longitude</code>.
     */
    public void setDropoffLongitude(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.dropoff_longitude</code>.
     */
    public Double getDropoffLongitude() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>ny_cab_data.cab_trip_data.dropoff_latitude</code>.
     */
    public void setDropoffLatitude(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>ny_cab_data.cab_trip_data.dropoff_latitude</code>.
     */
    public Double getDropoffLatitude() {
        return (Double) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Double, Double, Double, Double, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<String, String, String, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Double, Double, Double, Double, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CabTripData.CAB_TRIP_DATA.MEDALLION;
    }

    @Override
    public Field<String> field2() {
        return CabTripData.CAB_TRIP_DATA.HACK_LICENSE;
    }

    @Override
    public Field<String> field3() {
        return CabTripData.CAB_TRIP_DATA.VENDOR_ID;
    }

    @Override
    public Field<Integer> field4() {
        return CabTripData.CAB_TRIP_DATA.RATE_CODE;
    }

    @Override
    public Field<String> field5() {
        return CabTripData.CAB_TRIP_DATA.STORE_AND_FWD_FLAG;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return CabTripData.CAB_TRIP_DATA.PICKUP_DATETIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return CabTripData.CAB_TRIP_DATA.DROPOFF_DATETIME;
    }

    @Override
    public Field<Integer> field8() {
        return CabTripData.CAB_TRIP_DATA.PASSENGER_COUNT;
    }

    @Override
    public Field<Integer> field9() {
        return CabTripData.CAB_TRIP_DATA.TRIP_TIME_IN_SECS;
    }

    @Override
    public Field<Double> field10() {
        return CabTripData.CAB_TRIP_DATA.TRIP_DISTANCE;
    }

    @Override
    public Field<Double> field11() {
        return CabTripData.CAB_TRIP_DATA.PICKUP_LONGITUDE;
    }

    @Override
    public Field<Double> field12() {
        return CabTripData.CAB_TRIP_DATA.PICKUP_LATITUDE;
    }

    @Override
    public Field<Double> field13() {
        return CabTripData.CAB_TRIP_DATA.DROPOFF_LONGITUDE;
    }

    @Override
    public Field<Double> field14() {
        return CabTripData.CAB_TRIP_DATA.DROPOFF_LATITUDE;
    }

    @Override
    public String component1() {
        return getMedallion();
    }

    @Override
    public String component2() {
        return getHackLicense();
    }

    @Override
    public String component3() {
        return getVendorId();
    }

    @Override
    public Integer component4() {
        return getRateCode();
    }

    @Override
    public String component5() {
        return getStoreAndFwdFlag();
    }

    @Override
    public LocalDateTime component6() {
        return getPickupDatetime();
    }

    @Override
    public LocalDateTime component7() {
        return getDropoffDatetime();
    }

    @Override
    public Integer component8() {
        return getPassengerCount();
    }

    @Override
    public Integer component9() {
        return getTripTimeInSecs();
    }

    @Override
    public Double component10() {
        return getTripDistance();
    }

    @Override
    public Double component11() {
        return getPickupLongitude();
    }

    @Override
    public Double component12() {
        return getPickupLatitude();
    }

    @Override
    public Double component13() {
        return getDropoffLongitude();
    }

    @Override
    public Double component14() {
        return getDropoffLatitude();
    }

    @Override
    public String value1() {
        return getMedallion();
    }

    @Override
    public String value2() {
        return getHackLicense();
    }

    @Override
    public String value3() {
        return getVendorId();
    }

    @Override
    public Integer value4() {
        return getRateCode();
    }

    @Override
    public String value5() {
        return getStoreAndFwdFlag();
    }

    @Override
    public LocalDateTime value6() {
        return getPickupDatetime();
    }

    @Override
    public LocalDateTime value7() {
        return getDropoffDatetime();
    }

    @Override
    public Integer value8() {
        return getPassengerCount();
    }

    @Override
    public Integer value9() {
        return getTripTimeInSecs();
    }

    @Override
    public Double value10() {
        return getTripDistance();
    }

    @Override
    public Double value11() {
        return getPickupLongitude();
    }

    @Override
    public Double value12() {
        return getPickupLatitude();
    }

    @Override
    public Double value13() {
        return getDropoffLongitude();
    }

    @Override
    public Double value14() {
        return getDropoffLatitude();
    }

    @Override
    public CabTripDataRecord value1(String value) {
        setMedallion(value);
        return this;
    }

    @Override
    public CabTripDataRecord value2(String value) {
        setHackLicense(value);
        return this;
    }

    @Override
    public CabTripDataRecord value3(String value) {
        setVendorId(value);
        return this;
    }

    @Override
    public CabTripDataRecord value4(Integer value) {
        setRateCode(value);
        return this;
    }

    @Override
    public CabTripDataRecord value5(String value) {
        setStoreAndFwdFlag(value);
        return this;
    }

    @Override
    public CabTripDataRecord value6(LocalDateTime value) {
        setPickupDatetime(value);
        return this;
    }

    @Override
    public CabTripDataRecord value7(LocalDateTime value) {
        setDropoffDatetime(value);
        return this;
    }

    @Override
    public CabTripDataRecord value8(Integer value) {
        setPassengerCount(value);
        return this;
    }

    @Override
    public CabTripDataRecord value9(Integer value) {
        setTripTimeInSecs(value);
        return this;
    }

    @Override
    public CabTripDataRecord value10(Double value) {
        setTripDistance(value);
        return this;
    }

    @Override
    public CabTripDataRecord value11(Double value) {
        setPickupLongitude(value);
        return this;
    }

    @Override
    public CabTripDataRecord value12(Double value) {
        setPickupLatitude(value);
        return this;
    }

    @Override
    public CabTripDataRecord value13(Double value) {
        setDropoffLongitude(value);
        return this;
    }

    @Override
    public CabTripDataRecord value14(Double value) {
        setDropoffLatitude(value);
        return this;
    }

    @Override
    public CabTripDataRecord values(String value1, String value2, String value3, Integer value4, String value5, LocalDateTime value6, LocalDateTime value7, Integer value8, Integer value9, Double value10, Double value11, Double value12, Double value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CabTripDataRecord
     */
    public CabTripDataRecord() {
        super(CabTripData.CAB_TRIP_DATA);
    }

    /**
     * Create a detached, initialised CabTripDataRecord
     */
    public CabTripDataRecord(String medallion, String hackLicense, String vendorId, Integer rateCode, String storeAndFwdFlag, LocalDateTime pickupDatetime, LocalDateTime dropoffDatetime, Integer passengerCount, Integer tripTimeInSecs, Double tripDistance, Double pickupLongitude, Double pickupLatitude, Double dropoffLongitude, Double dropoffLatitude) {
        super(CabTripData.CAB_TRIP_DATA);

        set(0, medallion);
        set(1, hackLicense);
        set(2, vendorId);
        set(3, rateCode);
        set(4, storeAndFwdFlag);
        set(5, pickupDatetime);
        set(6, dropoffDatetime);
        set(7, passengerCount);
        set(8, tripTimeInSecs);
        set(9, tripDistance);
        set(10, pickupLongitude);
        set(11, pickupLatitude);
        set(12, dropoffLongitude);
        set(13, dropoffLatitude);
    }
}
