/*
 * This file is generated by jOOQ.
 */
package com.takehome.dao.jooq.domain;


import java.util.Arrays;
import java.util.List;

import com.takehome.dao.jooq.domain.tables.CabTripData;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NyCabData extends SchemaImpl {

    private static final long serialVersionUID = -2082191224;

    /**
     * The reference instance of <code>ny_cab_data</code>
     */
    public static final NyCabData NY_CAB_DATA = new NyCabData();

    /**
     * The table <code>ny_cab_data.cab_trip_data</code>.
     */
    public final CabTripData CAB_TRIP_DATA = CabTripData.CAB_TRIP_DATA;

    /**
     * No further instances allowed
     */
    private NyCabData() {
        super("ny_cab_data", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            CabTripData.CAB_TRIP_DATA);
    }
}
