/*
 * This file is generated by jOOQ.
 */
package com.takehome.dao.jooq.domain;


import com.takehome.dao.jooq.domain.tables.CabTripData;


/**
 * Convenience access to all tables in ny_cab_data
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ny_cab_data.cab_trip_data</code>.
     */
    public static final CabTripData CAB_TRIP_DATA = CabTripData.CAB_TRIP_DATA;
}
